namespace CargoDeckScanner;

// Alle Texte der App auf Deutsch und Englisch. Umschalten oben rechts in der App.
static class Lang
{
    public static bool En;

    public static string T(string key, params object[] a)
    {
        var s = Texts.TryGetValue(key, out var v) ? (En ? v.en : v.de) : key;
        return a.Length > 0 ? string.Format(s, a) : s;
    }

    static readonly Dictionary<string, (string de, string en)> Texts = new()
    {
        ["subtitle"] = ("Liest Preise vom Handelsterminal", "Reads prices from the trade terminal"),
        ["nav_scan"] = ("Erfassen", "Capture"),
        ["nav_set"] = ("Einstellungen", "Settings"),
        ["nav_help"] = ("Anleitung", "Guide"),
        ["pin"] = ("Im Vordergrund halten, kleines Fenster", "Keep on top, small window"),
        ["unpin"] = ("Zurück zum großen Fenster", "Back to the full window"),

        ["stopped"] = ("Gestoppt", "Stopped"),
        ["stopped_sub"] = ("Drück auf Starten, dann wartet Price Capture auf deine Taste.", "Press Start, then Price Capture waits for your key."),
        ["run_hot"] = ("Läuft", "Running"),
        ["run_hot_sub"] = ("Linke Strg + {0} am Terminal im Spiel drücken", "Press Left Ctrl + {0} at the terminal in game"),
        ["run_auto"] = ("Läuft automatisch", "Running automatically"),
        ["run_auto_sub"] = ("Alle {0} Sekunden, nur wenn ein Terminal zu sehen ist", "Every {0} seconds, only when a terminal is visible"),
        ["reading"] = ("Lese Terminal…", "Reading terminal…"),
        ["start"] = ("Starten", "Start"),
        ["stop"] = ("Stoppen", "Stop"),
        ["scan_now"] = ("Jetzt scannen", "Scan now"),
        ["scan_short"] = ("Scannen", "Scan"),
        ["auto"] = ("Automatik", "Auto mode"),
        ["auto_short"] = ("Auto", "Auto"),
        ["every"] = ("alle", "every"),
        ["seconds"] = ("Sekunden", "seconds"),
        ["last_title"] = ("Letzter Scan", "Last scan"),
        ["last_none"] = ("Noch nichts gescannt", "Nothing scanned yet"),
        ["last_ok"] = ("{0} Preise um {1}", "{0} prices at {1}"),
        ["last_look"] = ("Schau auf die Website, dort prüfen und übernehmen.", "Check the website, review and apply them there."),
        ["log_title"] = ("Verlauf", "History"),

        ["conn_title"] = ("Verbindung", "Connection"),
        ["url"] = ("Adresse der Website", "Website address"),
        ["code"] = ("Kopplungscode", "Pairing code"),
        ["code_hint"] = ("Steht auf der Website unter Einstellungen, Price Capture.", "Shown on the website under Settings, Price Capture."),
        ["keys_title"] = ("Tasten", "Keys"),
        ["keys_hint"] = ("Feld anklicken und neue Taste drücken", "Click a field and press the new key"),
        ["key_scan"] = ("Scannen", "Scan"),
        ["key_auto"] = ("Automatik an und aus", "Auto mode on and off"),
        ["ctrl"] = ("Linke Strg +", "Left Ctrl +"),
        ["save_restart"] = ("Speichern und neu starten", "Save and restart"),
        ["opt_title"] = ("Optionen", "Options"),
        ["opt_sound"] = ("Leise Töne", "Soft sounds"),
        ["opt_notify"] = ("Benachrichtigungen", "Notifications"),
        ["opt_autostart"] = ("Mit Windows starten", "Start with Windows"),
        ["opt_top"] = ("Immer im Vordergrund", "Always on top"),
        ["lang_title"] = ("Sprache", "Language"),
        ["engine_title"] = ("Texterkennung", "Text recognition"),
        ["engine_paddle"] = ("PaddleOCR, die gleiche Technik wie auf der Website", "PaddleOCR, the same technology as the website"),
        ["engine_win"] = ("Windows Texterkennung (PaddleOCR ging nicht: {0})", "Windows text recognition (PaddleOCR failed: {0})"),
        ["engine_load"] = ("wird geladen…", "loading…"),

        ["help_title"] = ("So funktioniert es", "How it works"),
        ["h1_t"] = ("Code holen", "Get the code"),
        ["h1"] = ("Öffne Cargo Deck im Browser, geh auf Einstellungen und kopiere den Code unter Price Capture.", "Open Cargo Deck in your browser, go to Settings and copy the code under Price Capture."),
        ["h2_t"] = ("Code eintragen", "Enter the code"),
        ["h2"] = ("Hier unter Einstellungen den Code einfügen. Die Adresse der Website stimmt schon.", "Paste the code here under Settings. The website address is already correct."),
        ["h3_t"] = ("Starten", "Start"),
        ["h3"] = ("Auf Starten drücken. Der Punkt oben wird grün, Price Capture wartet dann im Hintergrund.", "Press Start. The dot turns green and Price Capture waits in the background."),
        ["h4_t"] = ("Im Spiel scannen", "Scan in game"),
        ["h4"] = ("Am Handelsterminal Linke Strg + {0} drücken. Ein kurzer Ton sagt dir, dass das Bild gemacht ist. Gibt es weiter unten mehr Waren, im Terminal runterscrollen und gleich nochmal drücken, so oft du willst. Oder Automatik einschalten, dann liest er von selbst, sobald ein Terminal zu sehen ist.", "At the trade terminal press Left Ctrl + {0}. A short sound tells you the screenshot is taken. If there are more goods further down, scroll down in the terminal and press again right away, as often as you like. Or turn on auto mode, then it reads by itself whenever a terminal is visible."),
        ["h5_t"] = ("Auf der Website übernehmen", "Apply on the website"),
        ["h5"] = ("Der Scan Check erscheint auf der Website und wächst mit jedem weiteren Bild. Zwischendurch musst du nichts drücken. Am Ende einmal prüfen und übernehmen, dann fließen die Preise in deine Routen.", "The scan check shows up on the website and grows with every further screenshot. You don't need to press anything in between. At the end check it once and apply, then the prices flow into your routes."),
        ["tips_title"] = ("Tipps", "Tips"),
        ["tip1"] = ("Setz auf der Website deinen Standort, bei der Station auf „Ich bin hier“. Dann ist die Station sofort klar und alles geht schneller.", "Set your location on the website, click “I'm here” on the station. Then the station is clear right away and everything is faster."),
        ["tip2"] = ("Das Terminal sollte groß und gut lesbar im Bild sein. Fenster oder randloser Vollbildmodus gehen beide.", "The terminal should be large and readable on screen. Windowed and borderless fullscreen both work."),
        ["tip3"] = ("Mit der Nadel oben rechts bleibt ein kleines Fenster immer im Vordergrund, wie beim Windows Rechner.", "The pin at the top right keeps a small window always on top, like the Windows calculator."),
        ["tip4"] = ("Nach dem Starten kannst du das Fenster schließen oder minimieren. Price Capture läuft unten rechts neben der Uhr weiter.", "After starting you can close or minimize the window. Price Capture keeps running at the bottom right next to the clock."),
        ["open_site"] = ("Website öffnen", "Open website"),

        ["ready"] = ("Bereit", "Ready"),
        ["started"] = ("Gestartet, Linke Strg + {0} scannt", "Started, Left Ctrl + {0} scans"),
        ["stopped_log"] = ("Gestoppt", "Stopped"),
        ["busy"] = ("Noch beschäftigt, einen Moment", "Still busy, one moment"),
        ["held"] = ("Bild gemacht, wird gleich gelesen ({0} warten)", "Screenshot taken, read in a moment ({0} waiting)"),
        ["auto_on"] = ("Automatik an, alle {0} Sekunden", "Auto mode on, every {0} seconds"),
        ["auto_off"] = ("Automatik aus", "Auto mode off"),
        ["new_key"] = ("Neue Taste {0}, jetzt speichern", "New key {0}, save now"),
        ["saved_restart"] = ("Gespeichert, starte neu", "Saved, restarting"),
        ["save_fail"] = ("Speichern ging nicht {0}", "Saving failed {0}"),
        ["ocr_fail"] = ("Texterkennung ging nicht", "Text recognition failed"),
        ["ocr_err"] = ("Texterkennung Fehler {0}", "Text recognition error {0}"),
        ["send_fail"] = ("Senden fehlgeschlagen {0}", "Sending failed {0}"),
        ["unreach"] = ("Website nicht erreichbar, Adresse prüfen", "Website not reachable, check the address"),
        ["send_fail_n"] = ("Senden fehlgeschlagen, ist die Adresse richtig?", "Sending failed, is the address correct?"),
        ["rows_ok"] = ("{0} Preise erkannt {1}", "{0} prices recognized {1}"),
        ["rows_state"] = ("Letzter Scan {0}, {1} Preise", "Last scan {0}, {1} prices"),
        ["rows_notify"] = ("{0} Preise erkannt {1}, schau auf die Website", "{0} prices recognized {1}, check the website"),
        ["no_term"] = ("Kein Terminal erkannt", "No terminal recognized"),
        ["http_err"] = ("Website antwortet mit Fehler {0}", "Website answers with error {0}"),
        ["err"] = ("Fehler {0}", "Error {0}"),
        ["bad_url"] = ("Bitte die Adresse der Cargo Deck Website eintragen, zum Beispiel https://cargodeck.onrender.com", "Please enter the address of the Cargo Deck website, for example https://cargodeck.onrender.com"),
        ["bad_code"] = ("Der Kopplungscode hat 12 Zeichen. Du findest ihn auf der Website unter Einstellungen, Price Capture.", "The pairing code has 12 characters. You find it on the website under Settings, Price Capture."),
        ["tray_open"] = ("Öffnen", "Open"),
        ["tray_quit"] = ("Beenden", "Quit"),
        ["already"] = ("Cargo Deck Price Capture läuft schon. Du findest es unten rechts bei den Symbolen neben der Uhr.", "Cargo Deck Price Capture is already running. You find it at the bottom right next to the clock."),
        ["q_title"] = ("{0} Scans warten", "{0} scans waiting"),
        ["q_title1"] = ("1 Scan wartet", "1 scan waiting"),
        ["q_sub"] = ("Öffne Cargo Deck im Browser, dann werden sie automatisch hochgeladen.", "Open Cargo Deck in your browser, then they upload automatically."),
        ["q_log"] = ("Website nicht offen, Scan gespeichert ({0} warten)", "Website not open, scan stored ({0} waiting)"),
        ["q_code"] = ("{0} gespeicherte Scans für diesen Code", "{0} stored scans for this code"),
        ["q_notify"] = ("Scan gespeichert. Öffne Cargo Deck im Browser, dann wird er hochgeladen.", "Scan stored. Open Cargo Deck in your browser, then it gets uploaded."),
        ["q_sent"] = ("{0} gespeicherte Scans hochgeladen, prüf sie auf der Website", "{0} stored scans uploaded, check them on the website"),
        ["q_open"] = ("Website öffnen", "Open website"),
        ["ov_active"] = ("Aktive Route", "Active route"),
        ["ov_pins"] = ("Angepinnte Routen", "Pinned routes"),
        ["ov_stop"] = ("Stopp {0} von {1}", "Stop {0} of {1}"),
        ["ov_nopins"] = ("Noch keine Route angepinnt. Pinne sie auf der Website im Routenfenster an, neben Route starten.", "No route pinned yet. Pin them on the website in the route window, next to Start route."),
        ["ov_nstops"] = ("{0} Stopps", "{0} stops"),
        ["ov_back"] = ("Zurück", "Back"),
        ["ov_keys_pick"] = ("Strg+Alt+↑↓ wählen, Strg+Alt+→ aufklappen, Strg+Alt+Enter starten. Mit freier Maus einfach auf eine Route klicken.", "Ctrl+Alt+↑↓ select, Ctrl+Alt+→ expand, Ctrl+Alt+Enter start. With a free mouse just click a route."),
        ["ov_routes"] = ("Routen", "Routes"),
        ["ov_tap"] = ("Klick zeigt Stopps, Waren und SCU", "Click shows stops, goods and SCU"),
        ["ov_pick_start"] = ("Diese Route starten", "Start this route"),
        ["ov_each"] = ("je {0} · zusammen {1}", "{0} each · {1} total"),
        ["ov_each_short"] = ("je {0}", "{0} each"),
        ["ov_showall"] = ("alle zeigen", "show all"),
        ["ov_showless"] = ("weniger zeigen", "show less"),
        ["ov_none"] = ("Keine aktive Route", "No active route"),
        ["ov_none_sub"] = ("Starte eine Route auf der Website oder wähle hier eine angepinnte.", "Start a route on the website or pick a pinned one here."),
        ["ov_keys_idle"] = ("Strg+Alt+R Routen, Strg+Alt+O aus", "Ctrl+Alt+R routes, Ctrl+Alt+O hide"),
        ["ov_more_done"] = ("{0} Stopps erledigt", "{0} stops done"),
        ["ov_done"] = ("erledigt", "done"),
        ["ov_start"] = ("Start", "start"),
        ["ov_here"] = ("hier", "here"),
        ["ov_next"] = ("nächstes Ziel", "next stop"),
        ["ov_sell"] = ("Verkauf", "Sell"),
        ["ov_buy"] = ("Kauf", "Buy"),
        ["ov_more"] = ("noch {0} Stopps", "{0} more stops"),
        ["ov_prev"] = ("Zurück", "Back"),
        ["ov_finish"] = ("Fertig", "Done"),
        ["ov_nextbtn"] = ("Nächster Stopp", "Next stop"),
        ["ov_profit"] = ("Gewinn {0} aUEC", "Profit {0} aUEC"),
        ["ov_keys"] = ("Klick auf Stopp zeigt Preise", "Click a stop for prices"),
        ["ov_offline"] = ("Keine Verbindung zu Cargo Deck, versuche es weiter", "No connection to Cargo Deck, still trying"),
        ["ov_title"] = ("Overlay im Spiel · Beta", "In game overlay · Beta"),
        ["ov_show"] = ("Overlay über dem Spiel zeigen", "Show overlay over the game"),
        ["ov_hint"] = ("Strg+Alt+O ein und aus. Strg+Alt+→ und ← Stopp weiter oder zurück, Strg+Alt+N ab hier neu rechnen, Strg+Alt+R angepinnte Routen. Nimmt dem Spiel nie den Fokus, Star Citizen dafür im Modus Borderless starten. Oben am Titel lässt es sich verschieben.", "Ctrl+Alt+O on and off. Ctrl+Alt+→ and ← next or previous stop, Ctrl+Alt+N recalculate from here, Ctrl+Alt+R pinned routes. Never takes focus from the game, run Star Citizen in borderless mode. Drag it by the title."),
        ["ov_tray"] = ("Overlay", "Overlay"),
        ["ov_on"] = ("Overlay an", "Overlay on"),
        ["ov_off"] = ("Overlay aus", "Overlay off"),
        ["ov_replan"] = ("Neu rechnen", "Recalc"),
        ["ov_replan_wait"] = ("Cargo Deck rechnet ab hier neu…", "Cargo Deck is recalculating from here…"),
        ["ov_replan_web"] = ("Zum Neu rechnen Cargo Deck im Browser öffnen, dort wird gerechnet.", "Open Cargo Deck in your browser to recalculate, it runs there."),
        ["gl_title"] = ("Käufe aus der Game.log · Beta", "Trades from Game.log · Beta"),
        ["gl_on"] = ("Käufe und Verkäufe übernehmen", "Use purchases and sales"),
        ["gl_hint"] = ("Price Capture liest die Game.log von Star Citizen mit. Nach einem Kauf oder Verkauf am Terminal gehen nur Ort, Shop, Ware, Preis pro SCU, Menge und Uhrzeit an Cargo Deck. Dort prüfst du alles wie einen Scan. Dein Spielername und deine Spieler ID werden nie gesendet.", "Price Capture reads the Star Citizen Game.log. After a purchase or sale at a terminal only location, shop, commodity, price per SCU, amount and time go to Cargo Deck. You check it there like a scan. Your player name and player ID are never sent."),
        ["gl_pick"] = ("Datei wählen", "Choose file"),
        ["gl_none"] = ("Game.log nicht gefunden, bitte Datei wählen", "Game.log not found, please choose the file"),
        ["gl_found"] = ("Liest {0}", "Reading {0}"),
        ["gl_out"] = ("Game.log sendet {0} {1} SCU zu {2} aUEC an {3}", "Game.log sends {0} {1} SCU at {2} aUEC at {3}"),
        ["gl_buy"] = ("Kauf", "purchase"),
        ["gl_sell"] = ("Verkauf", "sale"),
        ["gl_ok"] = ("Erkannt {0} {1}, {2} aUEC, {3}", "Recognized {0} {1}, {2} aUEC, {3}"),
        ["gl_notify"] = ("Kauf aus der Game.log erkannt, prüf ihn auf der Website", "Trade from Game.log recognized, check it on the website"),
        ["gl_web"] = ("Website ist zu, der Scan wartet dort bis zu 15 Minuten", "Website is closed, the scan waits there for up to 15 minutes"),
        ["gl_fail"] = ("Game.log senden ging nicht {0}", "Sending Game.log trades failed {0}"),
        ["ov_cmd_fail"] = ("Overlay Befehl ging nicht {0}", "Overlay command failed {0}"),
        ["crash"] = ("Da ist etwas schiefgelaufen, Price Capture läuft aber weiter.", "Something went wrong, but Price Capture keeps running."),
        ["crash_log"] = ("Details stehen in %APPDATA%\\CargoDeck\\scanner-fehler.log", "Details are in %APPDATA%\\CargoDeck\\scanner-fehler.log"),
    };
}
